# 실행해 볼까요?
< 실행 : Ctrl + enter >

In [3]:
print('안녕하세요. Python을 실행해 보겠습니다!')
print('안녕하세요.', 'Python을 실행해 보겠습니다!')
print('1 + 1', '=', 1 + 1)

안녕하세요. Python을 실행해 보겠습니다!
안녕하세요. Python을 실행해 보겠습니다!
1 + 1 = 2


==============================================================================

Data Type 소개

In [8]:
# Data Type 소개

# Integer
a = 10
print("a의 type은?", type(a))

# String
b = 'python'
print("b의 type은?", type(b))
print("string은 내부 character에 하나하나 접근이 가능해요", b[0], b[5])

a의 type은? <class 'int'>
b의 type은? <class 'str'>
string은 내부 character에 하나하나 접근이 가능해요 p n


In [9]:
print(b[6])

IndexError: string index out of range

In [23]:
# List
c = [1, 2, 534, '356', 'ab', '하하', a, b, [5, -3]]
print(c)
print(c[2:]) # index 2부터 ('이상')
print(c[:4]) # index 4이전까지 ('미만')
print(len(c[1:5]))

[1, 2, 534, '356', 'ab', '하하', 10, 'python', [5, -3]]
[534, '356', 'ab', '하하', 10, 'python', [5, -3]]
[1, 2, 534, '356']
4


In [25]:
c.append('추가')
print(c)
c.pop()
print(c)
c.pop(3)
print(c)
c.insert(3,'insert')
print(c)
c[0] = '바꿀래'
print(c)

[1, 2, 534, 'insert', 'ab', '하하', 10, 'python', [5, -3], '추가']
[1, 2, 534, 'insert', 'ab', '하하', 10, 'python', [5, -3]]
[1, 2, 534, 'ab', '하하', 10, 'python', [5, -3]]
[1, 2, 534, 'insert', 'ab', '하하', 10, 'python', [5, -3]]
['바꿀래', 2, 534, 'insert', 'ab', '하하', 10, 'python', [5, -3]]


In [28]:
# tuple
d = ('1', 1, 3)
print(d)
d[0] = 5

('1', 1, 3)


TypeError: 'tuple' object does not support item assignment

In [33]:
# dictionary
e = {'a' : 5, 'b' : 6}
print(e)
print(e['a'])
e['c'] = 8
print(e)

{'a': 5, 'b': 6}
5
{'a': 5, 'b': 6, 'c': 8}


In [35]:
print(True, False)
print(5 > 6)
print(type('abc') == str)

True False
False
True


IF - ELIF - ELSE

In [36]:
A = 70

if A > 50:
    print('50초과')
elif A > 30:
    print('30초과')
elif A > 10:
    print('10초과')
else:
    print('10미만')

50초과


In [40]:
B = 40 

if B > 30:
    B -= 20    # B = B - 20
    print('B는?', B)
elif B == 20:
    print('실행 될까요 안될까요?')
    
B = 40 
if B > 30:
    B -= 20    # B = B - 20
    print('B는?', B)
if B == 20:
    print('이래야 실행이 되겠죠!')

B는? 20
B는? 20
이래야 실행이 되겠죠!


In [43]:
A, B, C = 50, 40, 30

if A > 30 and B > 30:
    print("C는?", C)
    if C > 30:
        print('C도 30보다 크네요!!')
    else:
        print('C는 30보다 크지는 않아요..')
        if C > A or C > B: 
            print('C가 A 또는 B보다는 크군요!')
        else:
            print('C는 A, B보다 작거나 같은 수인가봐요')
        if False:
            print('이건 실행 안되겠죠!')
        print('하지만 이건 실행됩니다!')
                    

C는? 30
C는 30보다 크지는 않아요..
C는 A, B보다 작거나 같은 수인가봐요
하지만 이건 실행됩니다!


FOR

In [55]:
for i in range(3):
    print(i)
print('===================')
D = ['하하','호호', '히히']
for j in D:
    print(j)
print('===================')  
for k in range(2, 10, 2):
    print(k)
print('===================')
for k in range(10):
    if k != 0 and k%2 == 0:
        print(k)

0
1
2
하하
호호
히히
2
4
6
8
2
4
6
8


In [49]:
# 간단 구구단

for n in range(1, 10, 1):
    for m in range(1, 10, 1):
        print(n, 'x', m, '=', n*m)

1 x 1 = 1
1 x 2 = 2
1 x 3 = 3
1 x 4 = 4
1 x 5 = 5
1 x 6 = 6
1 x 7 = 7
1 x 8 = 8
1 x 9 = 9
2 x 1 = 2
2 x 2 = 4
2 x 3 = 6
2 x 4 = 8
2 x 5 = 10
2 x 6 = 12
2 x 7 = 14
2 x 8 = 16
2 x 9 = 18
3 x 1 = 3
3 x 2 = 6
3 x 3 = 9
3 x 4 = 12
3 x 5 = 15
3 x 6 = 18
3 x 7 = 21
3 x 8 = 24
3 x 9 = 27
4 x 1 = 4
4 x 2 = 8
4 x 3 = 12
4 x 4 = 16
4 x 5 = 20
4 x 6 = 24
4 x 7 = 28
4 x 8 = 32
4 x 9 = 36
5 x 1 = 5
5 x 2 = 10
5 x 3 = 15
5 x 4 = 20
5 x 5 = 25
5 x 6 = 30
5 x 7 = 35
5 x 8 = 40
5 x 9 = 45
6 x 1 = 6
6 x 2 = 12
6 x 3 = 18
6 x 4 = 24
6 x 5 = 30
6 x 6 = 36
6 x 7 = 42
6 x 8 = 48
6 x 9 = 54
7 x 1 = 7
7 x 2 = 14
7 x 3 = 21
7 x 4 = 28
7 x 5 = 35
7 x 6 = 42
7 x 7 = 49
7 x 8 = 56
7 x 9 = 63
8 x 1 = 8
8 x 2 = 16
8 x 3 = 24
8 x 4 = 32
8 x 5 = 40
8 x 6 = 48
8 x 7 = 56
8 x 8 = 64
8 x 9 = 72
9 x 1 = 9
9 x 2 = 18
9 x 3 = 27
9 x 4 = 36
9 x 5 = 45
9 x 6 = 54
9 x 7 = 63
9 x 8 = 72
9 x 9 = 81


In [52]:
print(list(range(3)))

[0, 1, 2]


def

In [57]:
# 사칙연산을 하고 싶어요...

def ADD(a, b): return a + b
def DIF(a, b): return a - b
def MUL(a, b): return a * b
def DIV(a, b): return a / b

print('10 더하기 5는?', ADD(10, 5))
print('10 빼기 2 나누기 4 곱하기 -1 더하기 8은?',
     ADD(MUL(DIV(DIF(10, 2), 4), -1), 8))


10 더하기 5는? 15
10 빼기 2 나누기 4 곱하기 -1 더하기 8은? 6.0


In [63]:
def SIMPLE_FUC(A, B, C, D = 1):
    tmp = A + B
    tmp -= C
    if D == 1:
        print(A, '+', B, '-', C, '=', A + B - C)
    return tmp

SIMPLE_FUC(5, 2, 4)
a = SIMPLE_FUC(5, 2, 4, 0)
print(a)
    
print(tmp)

5 + 2 - 4 = 3
3


NameError: name 'tmp' is not defined

Library import

In [2]:
# Library Load

import numpy as np
import pandas as pd
from sklearn import linear_model
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier


Numpy

In [82]:
np1 = np.array([[1, 2, 3], [4, 5, 6]])
print(np1)
np2 = np.zeros((5, 3))
print(np2)
np3 = np.array(['abd'])
print(np3)
np4 = np.array([1, 'abc'])
print(np4)
np5 = np.array([[[2, 3], [4, 5]],[[6,7],[8,9]]])
print(np5)

[[1 2 3]
 [4 5 6]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
['abd']
['1' 'abc']
[[[2 3]
  [4 5]]

 [[6 7]
  [8 9]]]


In [91]:
print(np1[1, 2])
print(np1[:1,1:])
print(np1[:1,1])
np2[3, 1] = 5
print(np2)
print(np5[1,0,1])

6
[[2 3]]
[2]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 5. 0.]
 [0. 0. 0.]]
7


In [90]:
l1 = [1, 2, 3, 4]
l2 = [4, 5, 6, 7]
l_np = []
l_np.append(l1)
l_np.append(l2)
print(l_np)
l_np = np.asarray(l_np)
print(l_np)
print(l_np.shape)

[[1, 2, 3, 4], [4, 5, 6, 7]]
[[1 2 3 4]
 [4 5 6 7]]
(2, 4)


In [99]:
np6 = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])
np7 = np.array([9, 10, 11, 12])

# np8 = np.concatenate((np6, np7), axis = 0)
print(np6.shape, np7.shape) 
np8 = np.concatenate((np6, np7.reshape(1,4)), axis = 0)
print(np7.reshape(1,4).shape)
print(np8, np8.shape)

(2, 4) (4,)
(1, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] (3, 4)


In [110]:
np6 = np.arange(8).reshape(2,4)
np9 = np.array([9, 10])

# np8 = np.concatenate((np6, np9), axis = 1)
print(np6.shape, np9.shape) 
np10 = np.concatenate((np6, np9.reshape(2,-1)), axis = 1)
print(np9.reshape(2,-1).shape)
print(np10, np10.shape)

(2, 4) (2,)
(2, 1)
[[ 0  1  2  3  9]
 [ 4  5  6  7 10]] (2, 5)


In [111]:
np11 = np.array([[1, 2, 3], [-1, 0, 1], [-2, 1, 0]])
np12 = np.array([[0, 2, 1], [-1, -2, 2], [2, -1, 0]])
print(np11)
print(np12)
print('===== 더하기 =====')
print(np11 + np12)
print('===== 곱하기 =====')
print(np11 * np12)
print('===== 행렬곱 =====')
print(np.dot(np11, np12))
print('=== Transpose ===')
print(np11.T)

[[ 1  2  3]
 [-1  0  1]
 [-2  1  0]]
[[ 0  2  1]
 [-1 -2  2]
 [ 2 -1  0]]
===== 더하기 =====
[[ 1  4  4]
 [-2 -2  3]
 [ 0  0  0]]
===== 곱하기 =====
[[ 0  4  3]
 [ 1  0  2]
 [-4 -1  0]]
===== 행렬곱 =====
[[ 4 -5  5]
 [ 2 -3 -1]
 [-1 -6  0]]
=== Transpose ===
[[ 1 -1 -2]
 [ 2  0  1]
 [ 3  1  0]]


Pandas

In [149]:
prac_df = pd.read_csv('Pandas_prac.csv', encoding = 'cp949')
print(prac_df, type(prac_df))
# DataFrame Type
print('=========================')
prac_df_tmp = pd.DataFrame([[1,2], [3,4]], columns = ['col_1', 'col_2'])
print(prac_df_tmp)
print('=========================')
prac_df_tmp2 = pd.DataFrame(np12, 
                            columns = ['첫번째', '두번째', '세번째'])
print(prac_df_tmp2)                            


   NO  구분   메뉴 친구1  친구2  친구3  만족도
0   1  점심   라면  철수  NaN  NaN    5
1   2  저녁   곱창  길동   동진   영희    1
2   3  저녁   치킨  현지   보영  NaN    3
3   4  아침   김밥  철수  NaN  NaN    4
4   5  점심  샐러드  동기  NaN  NaN    1
5   6  점심   라면  동진  NaN  NaN    1
6   7  저녁   피자  지우  NaN  NaN    3
7   8  점심  파스타  웅이   이슬  NaN    2
8   9  저녁   보쌈  삼성  NaN  NaN    1
9  10  저녁   곱창  길동   영희  NaN    5 <class 'pandas.core.frame.DataFrame'>
   col_1  col_2
0      1      2
1      3      4
   첫번째  두번째  세번째
0    0    2    1
1   -1   -2    2
2    2   -1    0


In [150]:
print(prac_df['구분'][1:4])
print('==================')
print(prac_df[:][prac_df['메뉴'] == '곱창'])
print('==================')
print(prac_df[['구분', '메뉴', '만족도']][(prac_df['친구1'] == '동진') | (prac_df['친구2'] == '동진')]) 

# 참고
print((prac_df['친구1'] == '동진') | (prac_df['친구2'] == '동진'))

1    저녁
2    저녁
3    아침
Name: 구분, dtype: object
   NO  구분  메뉴 친구1 친구2  친구3  만족도
1   2  저녁  곱창  길동  동진   영희    1
9  10  저녁  곱창  길동  영희  NaN    5
   구분  메뉴  만족도
1  저녁  곱창    1
5  점심  라면    1
0    False
1     True
2    False
3    False
4    False
5     True
6    False
7    False
8    False
9    False
dtype: bool


In [151]:
# Columns
prac_col = list(prac_df.columns)
print(prac_col)

# 한글 데이터 숫자로 치환
prac_df['구분'] = prac_df.구분.map({'아침':0, '점심':1, '저녁': 2})
print(prac_df)

# fill in the missing values 
prac_df.친구2.fillna('', inplace=True) # Inplace = True면 데이터 자체 변경 
prac_df.친구3.fillna('', inplace=True) # Inplace = False면 단지 결과를 Print
print(prac_df)
# create a DataFrame of dummy variables
구분_dummies = pd.get_dummies(prac_df.구분, prefix='구분')

# concatenate the original DataFrame and the dummy DataFrame
prac_col.pop(0)
prac_col.pop(0)
prac_df= pd.concat([prac_df[prac_col], 구분_dummies], axis=1)
print(prac_df)

['NO', '구분', '메뉴', '친구1', '친구2', '친구3', '만족도']
   NO  구분   메뉴 친구1  친구2  친구3  만족도
0   1   1   라면  철수  NaN  NaN    5
1   2   2   곱창  길동   동진   영희    1
2   3   2   치킨  현지   보영  NaN    3
3   4   0   김밥  철수  NaN  NaN    4
4   5   1  샐러드  동기  NaN  NaN    1
5   6   1   라면  동진  NaN  NaN    1
6   7   2   피자  지우  NaN  NaN    3
7   8   1  파스타  웅이   이슬  NaN    2
8   9   2   보쌈  삼성  NaN  NaN    1
9  10   2   곱창  길동   영희  NaN    5
   NO  구분   메뉴 친구1 친구2 친구3  만족도
0   1   1   라면  철수            5
1   2   2   곱창  길동  동진  영희    1
2   3   2   치킨  현지  보영        3
3   4   0   김밥  철수            4
4   5   1  샐러드  동기            1
5   6   1   라면  동진            1
6   7   2   피자  지우            3
7   8   1  파스타  웅이  이슬        2
8   9   2   보쌈  삼성            1
9  10   2   곱창  길동  영희        5
    메뉴 친구1 친구2 친구3  만족도  구분_0  구분_1  구분_2
0   라면  철수            5     0     1     0
1   곱창  길동  동진  영희    1     0     0     1
2   치킨  현지  보영        3     0     0     1
3   김밥  철수            4     1     0     0
4  샐러드  동기       

In [65]:
def solution1(array, commands):
    answer = []
    
    # 참고로 list를 sort하는 방법은 list.sort()
    # ex) a = [3, 4, 1, 5]
    # a.sort()
    # print(a) --> [1, 3, 4, 5]
    
    return answer

array1 = [1, 5, 2, 6, 3, 7, 4]
commands1 = [[2, 5, 3], [4, 4, 1], [1, 7, 3]]
answer1 = [5, 6, 3]
print(solution1(array1, commands1) == answer1)

array2 = [0, -2, 5, 7, 8, 2, 5, 9, 3, 1, 5]
commands2 = [[1, 5, 2], [2, 8, 1], [5, 10, 3]]
answer2 = [-2, -2, 3]
print(solution1(array2, commands2) == answer2)


False
False


In [67]:
def solution2(arrangement):
    answer = 0
    
    # 이문제는 연속한 쌍이 어떤지가 중요합니다
    # 잘고민해보세요!
    
    return answer

arrangement1 = "()(((()())(())()))(())"
answer1 = 17
print(solution2(arrangement1) == answer1)

arrangement2 = "(((()()()(()())((())))()())())"
answer2 = 33
print(solution2(arrangement2) == answer2)

False
False
